# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="geckolib"
mandatory=true
versionRange=">=${geckolib_version_range}"
ordering="NONE"
side="BOTH"